import type { Session, User, Dashboard, UserList } from "./api";

// Every dynamic value is escaped before entering markup, including user names.
export function escape(value: unknown): string {
  return String(value ?? "").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]!));
}
export function layout(session: Session, title: string, content: string, welcome = false): string {
  const admin = session.multi && session.user?.role === "admin";
  const links = session.user
    ? `<a href="/dashboard" ${title === "Dashboard" ? 'aria-current="page"' : ""}>Dashboard</a>${admin ? `<a href="/users" ${title.includes("user") || title === "Users" ? 'aria-current="page"' : ""}>Users</a>` : ""}<a href="/account">Account</a><button class="button secondary" id="logout">Log out</button>`
    : `<a class="button secondary" href="/login">Log in</a><a class="button" href="/register">Register</a>`;
  return `<header class="navbar"><div class="nav-inner"><a class="brand" href="/"><img src="/logo.png" alt="CopyTyGo logo"><span>${escape(session.appName)}</span></a><nav aria-label="Main navigation">${links}</nav></div></header><main class="${welcome ? "welcome" : "main"}">${content}</main>`;
}
export function welcomeView(session: Session): string {
  return layout(session, "Welcome", `<section class="welcome-card"><p class="eyebrow">YOUR NEXT APPLICATION STARTS HERE</p><h1>${escape(session.appName)}</h1><p>Build applications with TypeScript and Go. Your project is ready. Start building from the CLI or open the local development Studio.</p><div class="welcome-actions"><a class="button" href="https://github.com/arfajhf/copytygo/blob/v${encodeURIComponent(session.version)}/README.md" target="_blank" rel="noreferrer">Documentation ↗</a>${session.showStudio ? '<a class="button outline" href="/__copytygo">Open Studio</a>' : ""}<a class="button outline" href="https://github.com/arfajhf/copytygo" target="_blank" rel="noreferrer">GitHub ↗</a></div><div class="features"><span>CopyTyGo ${escape(session.version)}</span><span>${escape(session.environment)}</span><span>TypeScript + Go</span></div></section>`, true);
}
export function field(name: string, label: string, type = "text", value = "", options: { autocomplete?: string; optional?: boolean; hint?: string } = {}): string {
  return `<label class="field">${escape(label)}<input name="${name}" type="${type}" value="${escape(value)}" ${options.optional ? "" : "required"} ${options.autocomplete ? `autocomplete="${options.autocomplete}"` : ""} ${type === "password" ? 'minlength="8" maxlength="72"' : ""}>${options.hint ? `<small>${escape(options.hint)}</small>` : ""}<small class="field-error" data-error="${name}"></small></label>`;
}
export function authView(session: Session, register: boolean): string {
  const title = register ? "Create account" : "Welcome back";
  return layout(session, title, `<section class="card form-card"><p class="eyebrow">${escape(session.appName)}</p><h1>${title}</h1><p>${register ? "A few details and you're ready to start." : "Log in to continue to your dashboard."}</p><form id="auth-form"><div id="form-error" class="notice error" role="alert" hidden></div>${register ? field("name", "Name", "text", "", { autocomplete: "name" }) : ""}${field("email", "Email", "email", "", { autocomplete: "email" })}${field("password", "Password", "password", "", { autocomplete: register ? "new-password" : "current-password", hint: "Use at least 8 characters." })}${register ? field("password_confirmation", "Confirm password", "password", "", { autocomplete: "new-password" }) : ""}<button class="button full" type="submit">${register ? "Create account" : "Log in"}</button></form><p class="form-footer">${register ? 'Already registered? <a href="/login">Log in</a>' : 'New here? <a href="/register">Create an account</a>'}</p></section>`);
}
export function dashboardView(session: Session, result: Dashboard): string {
  const admin = session.multi && result.user.role === "admin";
  return layout(session, "Dashboard", `<div class="page-heading"><div><p class="eyebrow">${admin ? "ADMIN WORKSPACE" : "YOUR WORKSPACE"}</p><h1>Hi, ${escape(result.user.name)}.</h1><p>Welcome to your dashboard.</p></div><span class="badge">${admin ? "Administrator" : session.multi ? "Member" : "Account"}</span></div>${admin && result.stats ? `<div class="stats"><article class="card"><p>Total users</p><strong>${result.stats.total}</strong></article><article class="card"><p>Administrators</p><strong>${result.stats.admins}</strong></article><article class="card"><p>Members</p><strong>${result.stats.members}</strong></article></div><section class="card"><h2>Manage your users</h2><p>Find accounts, update roles, or add a new user.</p><a class="button" href="/users">Manage users</a></section>` : `<section class="card"><h2>You're all set.</h2><p>This is your starting point. Customize this dashboard in frontend/src/auth/views.ts.</p><a class="button secondary" href="/account">View account</a></section>`}`);
}
export function accountView(session: Session): string {
  const user = session.user!;
  return layout(session, "Your account", `<div class="page-heading"><h1>Your account</h1></div><section class="card"><dl class="account"><dt>Name</dt><dd>${escape(user.name)}</dd><dt>Email</dt><dd>${escape(user.email)}</dd>${session.multi ? `<dt>Role</dt><dd>${escape(user.role)}</dd>` : ""}</dl></section>`);
}
export function usersView(session: Session, result: UserList): string {
  const search = new URLSearchParams(location.search).get("search") || "";
  const success = ({ created: "User created successfully.", updated: "User updated successfully.", deleted: "User deleted successfully." } as Record<string, string>)[new URLSearchParams(location.search).get("saved") || ""];
  const pageLink = (page: number) => `/users?${new URLSearchParams({ page: String(page), search })}`;
  return layout(session, "Users", `<div class="page-heading"><div><p class="eyebrow">ADMINISTRATION</p><h1>Users</h1><p>Monitor and manage ${result.total} accounts.</p></div><a class="button" href="/users/create">Add user</a></div><section class="card">${success ? `<div class="notice success" role="status">${success}</div>` : ""}<div id="form-error" class="notice error" role="alert" hidden></div><form class="search" method="GET" action="/users"><input name="search" aria-label="Search users" placeholder="Search name or email" value="${escape(search)}"><button class="button secondary">Search</button></form><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Actions</th></tr></thead><tbody>${result.users.map(user => `<tr><td>${escape(user.name)}</td><td>${escape(user.email)}</td><td><span class="badge">${escape(user.role)}</span></td><td class="row-actions"><a href="/users/${encodeURIComponent(user.id)}/edit">Edit</a>${user.id !== session.user?.id ? `<button class="text-danger" data-delete="${escape(user.id)}" data-name="${escape(user.name)}">Delete</button>` : '<span class="muted">Your account</span>'}</td></tr>`).join("") || '<tr><td colspan="4">No users found.</td></tr>'}</tbody></table></div><div class="pagination"><span>Page ${result.page}</span><div>${result.page > 1 ? `<a class="button secondary" href="${escape(pageLink(result.page - 1))}">Previous</a>` : ""}${result.page * result.pageSize < result.total ? `<a class="button secondary" href="${escape(pageLink(result.page + 1))}">Next</a>` : ""}</div></div></section>`);
}
export function userFormView(session: Session, user?: User): string {
  const title = user ? "Edit user" : "Add user";
  const own = user?.id === session.user?.id;
  return layout(session, title, `<div class="page-heading"><div><a href="/users">← Users</a><h1>${title}</h1></div></div><section class="card form-card user-form"><form id="user-form"><div id="form-error" class="notice error" role="alert" hidden></div>${field("name", "Name", "text", user?.name)}${field("email", "Email", "email", user?.email)}<label class="field">Role<select name="role" ${own ? "disabled" : ""}><option value="user" ${user?.role !== "admin" ? "selected" : ""}>Member</option><option value="admin" ${user?.role === "admin" ? "selected" : ""}>Administrator</option></select>${own ? '<small>You cannot remove your own administrator role.</small><input type="hidden" name="role" value="admin">' : ""}<small class="field-error" data-error="role"></small></label>${field("password", user ? "New password" : "Password", "password", "", { optional: !!user, autocomplete: "new-password", hint: user ? "Leave blank to keep the current password." : "Use at least 8 characters." })}${field("password_confirmation", "Confirm password", "password", "", { optional: !!user, autocomplete: "new-password" })}<div class="form-actions"><button class="button" type="submit">${user ? "Save changes" : "Create user"}</button><a class="button secondary" href="/users">Cancel</a></div></form></section>`);
}
