// Code generated by CopyTyGo. DO NOT EDIT.

package migrations

func RegisterGenerated() error {
	if err := Register20261003074008(); err != nil {
		return err
	}

	if err := Register20261005195535(); err != nil {
		return err
	}

	return nil
}
