package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func InstallAuth(mode, root string) error {
	if mode != "single" && mode != "multi" {
		return fmt.Errorf("copytygo: auth mode must be single or multi")
	}
	if err := os.MkdirAll(filepath.Join(root, "app", "auth"), 0755); err != nil {
		return err
	}
	roleField := ""
	if mode == "multi" {
		roleField = "\tRole string `json:\"role\"`\n"
	}
	model := fmt.Sprintf("package auth\n\ntype User struct {\n\tID int64 `json:\"id\"`\n\tName string `json:\"name\"`\n\tEmail string `json:\"email\"`\n\tPassword string `json:\"-\"`\n%s}\n", roleField)
	middleware := `package auth

import (
    copyauth "github.com/arfajhf/copytygo/v2/v2/auth"
    "github.com/arfajhf/copytygo/v2/v2/core"
)

func Middleware() core.Middleware {
    return copyauth.Middleware()
}

func RequireRole(roles ...string) core.Middleware {
    return copyauth.RequireRole(roles...)
}
`
	if err := os.WriteFile(filepath.Join(root, "app", "auth", "user.go"), []byte(model), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, "app", "auth", "middleware.go"), []byte(middleware), 0644); err != nil {
		return err
	}

	if err := makeAuthMigration(mode, filepath.Join(root, "database", "migrations")); err != nil {
		return err
	}

	if err := generateAuthRoutes(root); err != nil {
		return err
	}

	fmt.Printf("Auth scaffold installed (%s role).\n", mode)
	fmt.Println("Auth routes: POST /api/auth/register, POST /api/auth/login, GET /api/auth/me")
	return nil
}

func makeAuthMigration(mode, directory string) error {
	if err := os.MkdirAll(directory, 0755); err != nil {
		return err
	}

	entries, err := os.ReadDir(directory)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if !entry.IsDir() && strings.Contains(entry.Name(), "create_users_table") && filepath.Ext(entry.Name()) == ".go" {
			return nil
		}
	}

	now := time.Now()
	timestamp := now.Format("20060102_150405")
	functionID := now.Format("20060102150405")
	filename := timestamp + "_create_users_table.go"
	path := filepath.Join(directory, filename)

	roleColumn := ""
	if mode == "multi" {
		roleColumn = "\t\t\t\t\ttable.String(\"role\").DefaultValue(\"user\")\n"
	}

	content := fmt.Sprintf(`package migrations

import (
	"github.com/arfajhf/copytygo/v2/v2/database/migration"
	"github.com/arfajhf/copytygo/v2/v2/database/schema"
)

func Register%s() error {
	return migration.Register(
		%q,
		func() *schema.Blueprint {
			return schema.Create("users", func(table *schema.Table) {
				table.ID()
				table.String("name")
				table.String("email").Unique()
				table.String("password")
%s				table.Timestamps()
			})
		},
		func() *schema.Blueprint {
			return schema.Drop("users")
		},
	)
}
`, functionID, timestamp+"_create_users_table", roleColumn)

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return err
	}

	return GenerateMigrationRegistry(directory)
}


func generateAuthRoutes(root string) error {
	module, err := projectModule(filepath.Join(root, "go.mod"))
	if err != nil {
		return err
	}
	_ = module

	routeDir := filepath.Join(root, "routes")
	if err := os.MkdirAll(routeDir, 0755); err != nil {
		return err
	}

	content := `// Code generated by CopyTyGo. DO NOT EDIT.

package routes

import (
	copyauth "github.com/arfajhf/copytygo/v2/v2/auth"
	"github.com/arfajhf/copytygo/v2/v2/core"
)

func RegisterAuth(app *core.Application) {
	copyauth.Routes(app, "user")
}
`

	if err := os.WriteFile(filepath.Join(routeDir, "auth.go"), []byte(content), 0644); err != nil {
		return err
	}

	webPath := filepath.Join(routeDir, "web.go")
	raw, err := os.ReadFile(webPath)
	if err != nil {
		return err
	}

	web := string(raw)
	if strings.Contains(web, "RegisterAuth(app)") {
		return nil
	}

	needle := "func Register(app *core.Application) {"
	index := strings.Index(web, needle)
	if index < 0 {
		return fmt.Errorf("copytygo: routes.Register function not found")
	}
	insertAt := index + len(needle)
	web = web[:insertAt] + "\n    RegisterAuth(app)" + web[insertAt:]

	return os.WriteFile(webPath, []byte(web), 0644)
}
