package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var jobMarkerPattern = regexp.MustCompile(`^// copytygo:job ([A-Za-z][A-Za-z0-9_]*)$`)

type generatedJob struct {
	Name string
	Type string
}

func GenerateJobRegistry(directory string) error {
	entries, err := os.ReadDir(directory)
	if err != nil {
		if os.IsNotExist(err) {
			if err := os.MkdirAll(directory, 0755); err != nil {
				return err
			}
			entries = []os.DirEntry{}
		} else {
			return err
		}
	}

	jobs := make([]generatedJob, 0)
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" || entry.Name() == "registry.go" || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		file, err := os.Open(filepath.Join(directory, entry.Name()))
		if err != nil {
			return err
		}

		scanner := bufio.NewScanner(file)
		jobName := ""
		typeName := ""
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if matches := jobMarkerPattern.FindStringSubmatch(line); len(matches) == 2 {
				jobName = matches[1]
			}
			if strings.HasPrefix(line, "type ") && strings.HasSuffix(line, " struct{}") {
				fields := strings.Fields(line)
				if len(fields) >= 2 {
					typeName = fields[1]
				}
			}
		}
		_ = file.Close()

		if err := scanner.Err(); err != nil {
			return err
		}
		if jobName != "" && typeName != "" {
			jobs = append(jobs, generatedJob{Name: jobName, Type: typeName})
		}
	}

	sort.Slice(jobs, func(i, j int) bool { return jobs[i].Name < jobs[j].Name })

	var out strings.Builder
	out.WriteString("// Code generated by CopyTyGo. DO NOT EDIT.\n\n")
	out.WriteString("package jobs\n\n")
	out.WriteString("import \"github.com/arfajhf/copytygo/v4/queue\"\n\n")
	out.WriteString("func Register(registry *queue.Registry) error {\n")
	out.WriteString("\tif registry == nil { registry = queue.DefaultRegistry }\n")
	for _, job := range jobs {
		out.WriteString(fmt.Sprintf("\tif err := registry.Register(%q, %s{}.Handle); err != nil { return err }\n", job.Name, job.Type))
	}
	out.WriteString("\treturn nil\n")
	out.WriteString("}\n")

	return os.WriteFile(filepath.Join(directory, "registry.go"), []byte(out.String()), 0644)
}
