package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var generatedMigrationPattern = regexp.MustCompile(
	`^(\d{8})_(\d{6})_([a-z][a-z0-9_]*)\.go$`,
)

type migrationRegistryEntry struct {
	Filename string
	Function string
}

func GenerateMigrationRegistry(
	directory string,
) error {

	entries, err := os.ReadDir(directory)

	if err != nil {
		return fmt.Errorf(
			"unable to read migration directory: %w",
			err,
		)
	}

	migrations := make(
		[]migrationRegistryEntry,
		0,
	)

	for _, entry := range entries {

		if entry.IsDir() {
			continue
		}

		name := entry.Name()

		matches :=
			generatedMigrationPattern.FindStringSubmatch(
				name,
			)

		if len(matches) != 4 {
			continue
		}

		functionID :=
			matches[1] + matches[2]

		migrations = append(
			migrations,
			migrationRegistryEntry{
				Filename: name,

				Function: "Register" +
					functionID,
			},
		)
	}

	sort.Slice(
		migrations,
		func(i int, j int) bool {
			return migrations[i].Filename <
				migrations[j].Filename
		},
	)

	content := buildRegistryContent(
		migrations,
	)

	path := filepath.Join(
		directory,
		"registry.go",
	)

	if err := os.WriteFile(
		path,
		[]byte(content),
		0644,
	); err != nil {

		return fmt.Errorf(
			"unable to write migration registry: %w",
			err,
		)
	}

	return nil
}

func buildRegistryContent(
	migrations []migrationRegistryEntry,
) string {

	var builder strings.Builder

	builder.WriteString(
		"// Code generated by CopyTyGo. DO NOT EDIT.\n\n",
	)

	builder.WriteString(
		"package migrations\n\n",
	)

	builder.WriteString(
		"func RegisterGenerated() error {\n",
	)

	for _, item := range migrations {

		builder.WriteString(
			fmt.Sprintf(
				"\tif err := %s(); err != nil {\n",
				item.Function,
			),
		)

		builder.WriteString(
			"\t\treturn err\n",
		)

		builder.WriteString(
			"\t}\n\n",
		)
	}

	builder.WriteString(
		"\treturn nil\n",
	)

	builder.WriteString(
		"}\n",
	)

	return builder.String()
}
