package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var resourceMarkerPattern = regexp.MustCompile(`^// copytygo:resource ([A-Za-z_][A-Za-z0-9_]*)$`)

type generatedResourceRoute struct {
	Resource       string
	ControllerType string
}

func GenerateResourceRoutes(root string) error {
	module, err := projectModule(filepath.Join(root, "go.mod"))
	if err != nil {
		return err
	}

	controllerDir := filepath.Join(root, "app", "controllers")
	entries, err := os.ReadDir(controllerDir)
	if err != nil {
		return fmt.Errorf("copytygo: unable to read controllers: %w", err)
	}

	resources := make([]generatedResourceRoute, 0)
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
			continue
		}

		path := filepath.Join(controllerDir, entry.Name())
		file, err := os.Open(path)
		if err != nil {
			return err
		}

		scanner := bufio.NewScanner(file)
		resource := ""
		controllerType := ""
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if matches := resourceMarkerPattern.FindStringSubmatch(line); len(matches) == 2 {
				resource = matches[1]
			}
			if strings.HasPrefix(line, "type ") && strings.Contains(line, "Controller struct") {
				fields := strings.Fields(line)
				if len(fields) >= 2 {
					controllerType = fields[1]
				}
			}
		}
		_ = file.Close()
		if err := scanner.Err(); err != nil {
			return err
		}

		if resource != "" && controllerType != "" {
			resources = append(resources, generatedResourceRoute{
				Resource:       resource,
				ControllerType: controllerType,
			})
		}
	}

	sort.Slice(resources, func(i, j int) bool {
		return resources[i].Resource < resources[j].Resource
	})

	if err := os.MkdirAll(filepath.Join(root, "routes"), 0755); err != nil {
		return err
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by CopyTyGo. DO NOT EDIT.\n\n")
	builder.WriteString("package routes\n\n")
	if len(resources) > 0 {
		builder.WriteString("import (\n")
		builder.WriteString("\t\"" + module + "/app/controllers\"\n")
		builder.WriteString("\t\"github.com/arfajhf/copytygo/core\"\n")
		builder.WriteString(")\n\n")
	} else {
		builder.WriteString("import \"github.com/arfajhf/copytygo/core\"\n\n")
	}

	builder.WriteString("func RegisterGeneratedResources(app *core.Application) {\n")
	for _, item := range resources {
		builder.WriteString(fmt.Sprintf(
			"\tapp.Resource(\"/%s\", controllers.%s{})\n",
			item.Resource,
			item.ControllerType,
		))
	}
	builder.WriteString("}\n")

	if err := os.WriteFile(
		filepath.Join(root, "routes", "resources.go"),
		[]byte(builder.String()),
		0644,
	); err != nil {
		return err
	}

	return ensureGeneratedResourceCall(filepath.Join(root, "routes", "web.go"))
}

func ensureGeneratedResourceCall(path string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	content := string(raw)
	if strings.Contains(content, "RegisterGeneratedResources(app)") {
		return nil
	}

	index := strings.Index(content, "func Register(app *core.Application) {")
	if index < 0 {
		return fmt.Errorf("copytygo: routes.Register function not found")
	}

	insertAt := index + len("func Register(app *core.Application) {")
	content = content[:insertAt] + "\n    RegisterGeneratedResources(app)" + content[insertAt:]

	return os.WriteFile(path, []byte(content), 0644)
}

func projectModule(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			module := strings.TrimSpace(strings.TrimPrefix(line, "module "))
			if module != "" {
				return module, nil
			}
		}
	}
	return "", fmt.Errorf("copytygo: module path not found in go.mod")
}
